import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#F8F8F8",
    paddingBottom: 80, 
  },
  header: {
    textAlign: "center",
    fontSize: 20,
    fontWeight: "bold",
    marginVertical: 15,
    fontFamily: "Poppins-SemiBold",
  },
  pointsContainer: {
    flexDirection: "row",
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#2E44FF",
    borderRadius: 10,
    padding: 12,
    marginHorizontal: 16,
    backgroundColor: "#fff",
  },
  giftIcon: {
    width: 40,
    height: 40,
    resizeMode: "contain",
  },
  pointsText: {
    flex: 1,
    marginLeft: 10,
    fontSize: 18,
    fontWeight: "bold",
    color: "#2E44FF",
    fontFamily: "Poppins-SemiBold",
  },
  arrow: {
    fontSize: 22,
    color: "#2E44FF",
  },

  gradientContainer: {
    flex: 1,
    marginTop: 20,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    paddingBottom: 20,
  },

  sectionHeader: {
    paddingVertical: 10,
    paddingHorizontal: 16,
    marginTop: 10,
  },
  sectionTitle: {
    fontSize: 14,
    fontWeight: "bold",
    color: "#fff",
    textAlign: "center",
    fontFamily: "Poppins-SemiBold",
  },
  sectionSubtitle: {
    fontSize: 18,
    color: "#fff",
    textAlign: "center",
    fontFamily: "Poppins-SemiBold",
  },
  taskCard: {
    width: 260,
    backgroundColor: "#fff",
    borderRadius: 12,
    padding: 14,
    marginRight: 12,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.1,
    shadowRadius: 5,
    elevation: 4,
    
  },
  taskHeader: {
    fontSize: 12,
    fontWeight: "600",
    color: "#000",
    alignSelf: "flex-start",
    marginBottom: 6,
    fontFamily: "Poppins-Medium",
  },
  row: {
    flexDirection: "row",
    alignItems: "center",
  },
  taskTitle: {
    fontSize: 16,
    fontWeight: "700",
    color: "#1877F2",
    marginBottom: 6,
    fontFamily: "Poppins-SemiBold",
  },
  pointBox: {
    flexDirection: "row",
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#ddd",
    borderRadius: 8,
    paddingVertical: 4,
    paddingHorizontal: 10,
    marginBottom: 8,
    backgroundColor: "#fff",
    alignSelf: "flex-start",
  },
  star: {
    fontSize: 16,
    marginRight: 6,
  },
  taskPoints: {
    fontSize: 14,
    fontWeight: "bold",
    color: "#2E44FF",
    fontFamily: "Poppins-SemiBold",
  },
  startButton: {
    backgroundColor: "#2E44FF",
    paddingVertical: 6,
    paddingHorizontal: 14,
    borderRadius: 6,
    alignSelf: "flex-start",
  },
  startText: {
    color: "#fff",
    fontWeight: "bold",
    fontSize: 14,
    fontFamily: "Poppins-SemiBold",
  },
  taskImage: {
    width: 80,
    height: 80,
    resizeMode: "contain",
    marginLeft: 10,
  },

  rewardCard: {
    backgroundColor: "#fff",
    borderRadius: 12,
    padding: 10,
    marginVertical: 16,
    alignItems: "center",
    width: "32%",
    shadowColor: "#000",
    shadowOpacity: 0.25,
    shadowOffset: { width: 0, height: 2 },
    shadowRadius: 6,
    elevation: 6,
    transform: [{ translateY: -6 }],
  },
  rewardImage: {
    width: 50,
    height: 50,
    resizeMode: "contain",
  },
  rewardTitle: {
    marginVertical: 10,
    fontSize: 16,
    fontWeight: "bold",
    textAlign: "center",
    color: "#24aae9ff",
    fontFamily: "Poppins-SemiBold",
  },
  rewardFooter: {
    marginTop: 8,
    alignItems: "center",
  },
  rewardPoints: {
    fontSize: 16,
    fontWeight: "bold",
    color: "#2E44FF",
    fontFamily: "Poppins-SemiBold",
  },
});

export default styles;
